<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var $block \Magento\Framework\View\Element\Html\Links */
?>
<?php /** @var $block \Magento\Customer\Block\Account\Navigation */ ?>
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php /* @escapeNotVerified */ echo __('My Account'); ?></h3>
    </div>

    <div class="panel-body">
        <ul class="nav nav-pills nav-stacked">
            <?php echo $block->getChildHtml();?>
        </ul>
    </div>
</div>