<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Wishlist\Block\Catalog\Product\View\Addto\Wishlist */
?>
<?php if ($block->isWishListAllowed()) : ?>
    <div class="col-xs-12 col-md-4">
        <a href="#"
           class="action towishlist"
           data-post='<?php /* @escapeNotVerified */ echo $block->getWishlistParams(); ?>'
           data-action="add-to-wishlist">
            <span class="glyphicon glyphicon-heart"></span>
            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
        </a>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?php /* @escapeNotVerified */ echo $block->getWishlistOptionsJson() ?>
        }
    }
</script>
