<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<?php $columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'dropdown-menu', $columnsLimit) ?>

<ul class="nav navbar-nav">
    <?php /* @escapeNotVerified */ echo $_menu; ?>
    <?php /* @escapeNotVerified */ echo $block->getChildHtml(); ?>
</ul>
