<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Last ordered items sidebar
 *
 * @var $block \Magento\Sales\Block\Reorder\Sidebar
 */
?>
<div class="panel panel-default" data-bind="scope: 'lastOrderedItems'">
    <div class="panel-heading" data-bind="css: {'no-display': !lastOrderedItems().items || lastOrderedItems().items.length === 0}">
        <strong id="block-reorder-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Recently Ordered') ?></strong>
    </div>

    <div class="panel-body"
         data-bind="css: {'no-display': !lastOrderedItems().items || lastOrderedItems().items.length === 0}"
         aria-labelledby="block-reorder-heading">
        <form method="post" class="form reorder"
              action="<?php /* @escapeNotVerified */ echo $block->getFormActionUrl() ?>" id="reorder-validate-detail">
            <strong class="subtitle"><?php /* @escapeNotVerified */ echo __('Last Ordered Items') ?></strong>
            <div id="cart-sidebar-reorder" class="product-items product-items-names"
                data-bind="foreach: lastOrderedItems().items">
                <div class="field item choice no-display" data-bind="css: {'no-display': !is_saleable}">
                    <div class="checkbox">
                        <label data-bind="attr: {'for': 'reorder-item-' + id}">
                        
                            <input type="checkbox" name="order_items[]" data-bind="attr: {id: 'reorder-item-' + id, value: id}"
                            title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>"
                            class="checkbox" data-validate='{"validate-one-checkbox-required-by-name": true}'/>

                            <strong class="product-item-name">
                                <a data-bind="attr: {href: url}" class="product-item-link">
                                    <span data-bind="text: name"></span>
                                </a>
                            </strong>
                        </label>
                    </div>
                </div>
            </div>

            <div id="cart-sidebar-reorder-advice-container"></div>

            <!--div class="primary no-display" data-bind="css: {'no-display': !lastOrderedItems().isShowAddToCart}"-->
                <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Add to Cart') ?>" class="btn btn-primary">
                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                </button>
            <!--/div-->

            <a class="btn btn-info" href="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/account') ?>">
                <span><?php /* @escapeNotVerified */ echo __('View All'); ?></span>
            </a>
        </form>
    </div>
    <script>
    require(["jquery", "mage/mage"], function(jQuery){
        jQuery('#reorder-validate-detail').mage('validation', {
            errorPlacement: function(error, element) {
                error.appendTo('#cart-sidebar-reorder-advice-container');
            }
        });
    });
    </script>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "lastOrderedItems": {
                    "component": "Magento_Sales/js/view/last-ordered-items"
                }
            }
        }
    }
}
</script>
