<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Temlate for \Magento\Customer\Block\Address\Book block
 * @var $block \Magento\Customer\Block\Address\Book
 */
?>
<div class="panel panel-default panel-addresses-default">
    <div class="panel-heading"><strong><?php /* @escapeNotVerified */ echo __('Default Addresses') ?></strong></div>
    <div class="panel-body">
        <div class="container-fluid">
            <div class="row">
                <?php if ($_pAddsses = $block->getDefaultBilling()): ?>
                        <div class="col-sm-6">
                            <div class="panel panel-primary panel-address-billing">
                                <div class="panel-heading">
                                    <?php /* @escapeNotVerified */ echo __('Default Billing Address') ?>
                                </div>
                                <div class="panel-body">
                                    <address>
                                        <?php echo $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                                    </address>
                                </div>
                                <div class="panel-actions">
                                    <a class="btn btn-link edit" href="<?php /* @escapeNotVerified */ echo $block->getAddressEditUrl($_pAddsses) ?>">
                                        <span><?php /* @escapeNotVerified */ echo __('Change Billing Address') ?></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    <?php else: ?>
                        <div class="panel panel-primary panel-billing-address">
                            <div class="panel-heading"><?php /* @escapeNotVerified */ echo __('Default Billing Address') ?></div>
                            <div class="panel-body">
                                <p><?php /* @escapeNotVerified */ echo __('You have no default billing address in your address book.') ?></p>
                            </div>
                        </div>
                <?php endif ?>

                <?php if ($_pAddsses = $block->getDefaultShipping()): ?>
                    <div class="col-sm-6">
                        <div class="panel panel-primary panel-address-shipping">
                            <div class="panel-heading">
                                <span><?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?></span>
                            </div>
                            <div class="panel-body">
                                <address>
                                    <?php echo $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                                </address>
                            </div>
                            <div class="panel-actions">
                                <a class="btn btn-link edit" href="<?php /* @escapeNotVerified */ echo $block->getAddressEditUrl($_pAddsses) ?>">
                                    <span><?php /* @escapeNotVerified */ echo __('Change Shipping Address') ?></span>
                                </a>
                            </div>
                        </div>
                    </div>
                <?php else: ?>
                    <div class="panel panel-primary panel-shipping-address">
                        <strong class="panel-heading"><span><?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?></span></strong>
                        <div class="panel-body">
                            <p><?php /* @escapeNotVerified */ echo __('You have no default shipping address in your address book.') ?></p>
                        </div>
                    </div>
                <?php endif ?>
            </div>  
        </div>
    </div>
</div>

<div class="panel panel-default panel-addresses-list">
    <div class="panel-heading"><strong><?php /* @escapeNotVerified */ echo __('Additional Address Entries') ?></strong></div>
    <div class="panel-body">
        <?php if ($_pAddsses = $block->getAdditionalAddresses()): ?>
            <div class="container-fluid items addresses">
                <div class="row">
                    <?php foreach ($_pAddsses as $_address): ?>
                        <div class="col-sm-6">
                           <div class="panel panel-default">
                               <div class="panel-heading">
                                   <?php /* @escapeNotVerified */ echo __('Address details') ?>
                               </div>
                               <div class="panel-body">
                                    <address>
                                        <?php echo $block->getAddressHtml($_address) ?><br />
                                    </address>
                                    <div class="item actions">
                                        <a class="btn btn-link edit" href="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/address/edit', ['id' => $_address->getId()]) ?>"><span><?php /* @escapeNotVerified */ echo __('Edit Address') ?></span></a>
                                        <a class="btn btn-link delete" href="#" role="delete-address" data-address="<?php /* @escapeNotVerified */ echo $_address->getId() ?>"><span><?php /* @escapeNotVerified */ echo __('Delete Address') ?></span></a>
                                    </div>
                               </div>
                           </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        <?php else: ?>
            <p class="empty"><?php /* @escapeNotVerified */ echo __('You have no other address entries in your address book.') ?></p>
        <?php endif ?>
    </div>
</div>
<div class="actions-toolbar">
        <button type="button" role="add-address" title="<?php /* @escapeNotVerified */ echo __('Add New Address') ?>" class="btn btn-primary primary add"><?php /* @escapeNotVerified */ echo __('Add New Address') ?></button>
        <a class="btn btn-link back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><?php /* @escapeNotVerified */ echo __('Back') ?></a>
</div>
<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "li.item a[role='delete-address']",
                "deleteUrlPrefix": "<?php /* @escapeNotVerified */ echo $block->getDeleteUrl() ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?php /* @escapeNotVerified */ echo $block->getAddAddressUrl() ?>"
            }
        }
    }
</script>
