<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Address $block */
?>
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title"><?php /* @escapeNotVerified */ echo __('Address Book') ?></h3>
        </div>

        <div class="panel-body">
            <div class="box box-billing-address">
                <strong class="box-title">
                    <span><?php /* @escapeNotVerified */ echo __('Default Billing Address') ?></span>
                </strong>
                <div class="box-content">
                    <address>
                        <?php echo $block->getPrimaryBillingAddressHtml() ?>
                    </address>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getPrimaryBillingAddressEditUrl() ?>" data-ui-id="default-billing-edit-link"><span><?php /* @escapeNotVerified */ echo __('Edit Address') ?></span></a>
                </div>
            </div>
            <div class="box box-shipping-address">
                <strong class="box-title">
                    <span><?php /* @escapeNotVerified */ echo __('Default Shipping Address') ?></span>
                </strong>
                <div class="box-content">
                    <address>
                        <?php echo $block->getPrimaryShippingAddressHtml() ?>
                    </address>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?php /* @escapeNotVerified */ echo $block->getPrimaryShippingAddressEditUrl() ?>" data-ui-id="default-shipping-edit-link"><span><?php /* @escapeNotVerified */ echo __('Edit Address') ?></span></a>
                </div>
            </div>
        </div>
    </div>
</div>