<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_product = $block->getProduct() ?>
<?php if ($block->canEmailToFriend()): ?>
    <div class="col-xs-12 col-md-4">
        <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
           class="action mailto friend">
            <span class="glyphicon glyphicon-envelope"></span>
            <span><?php /* @escapeNotVerified */ echo __('Email') ?></span>
        </a>
    </div>
<?php endif; ?>
