<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

?>
<div class="col-lg-6 col-lg-offset-3">
    <div class="alert alert-info">
        <?php /* @escapeNotVerified */ echo __('Please enter your email address below to receive a password reset link.'); ?>     
    </div>

    <form class="form password forget"
          action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/forgotpasswordpost') ?>"
          method="post"
          id="form-validate"
          data-mage-init='{"validation":{}}'>
        <div class="form-group">
            <label for="email_address"><span><?php /* @escapeNotVerified */ echo __('Email Address') ?></span></label>
            <input type="email" name="email" alt="email" id="email_address" class="form-control" value="<?php echo $block->escapeHtml($block->getEmailValue()) ?>" data-validate="{required:true, 'validate-email':true}">
        </div>

        <?php echo $block->getChildHtml('form_additional_info'); ?>

        <button type="submit" class="btn btn-primary">
            <span><?php /* @escapeNotVerified */ echo __('Reset My Password') ?></span>
        </button>

        <a class="btn btn-danger" href="<?php /* @escapeNotVerified */ echo $block->getLoginUrl() ?>">
            <span><?php /* @escapeNotVerified */ echo __('Go back') ?></span>
        </a>
    </form>
</div>