<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="col-md-6">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <?php /* @escapeNotVerified */ echo __('Registered Customers') ?>
            </h3>
        </div>

        <div class="panel-body">
            <form class="form form-login"
                  action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
                  method="post"
                  id="login-form"
                  data-mage-init='{"validation":{}}'>
                <?php echo $block->getBlockHtml('formkey'); ?>   
                <div class="alert alert-info">
                    <?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?>
                </div>
                
                <div class="form-group">
                    <label for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                    <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> id="email" type="email" class="form-control" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">
                </div>

                <div class="form-group">
                    <label for="pass"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                    <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) :?> autocomplete="off"<?php endif; ?> class="form-control" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true}">
                </div>

                <?php echo $block->getChildHtml('form_additional_info'); ?>
                
                <button type="submit" class="btn btn-primary" name="send" id="send2">
                    <span><?php /* @escapeNotVerified */ echo __('Sign In') ?></span>
                </button>

                <a class="btn btn-danger" href="<?php /* @escapeNotVerified */ echo $block->getForgotPasswordUrl() ?>">
                    <span><?php /* @escapeNotVerified */ echo __('Forgot Your Password?') ?></span>
                </a>
            </form>
        </div>
    </div>
</div>