<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php echo $block->getChildHtml('form_before')?>
<form class="form" action="<?php /* @escapeNotVerified */ echo $block->getAction() ?>" method="post" id="form-validate">
    <fieldset class="fieldset">
        <?php echo $block->getBlockHtml('formkey')?>
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Subscription option') ?></span></legend><br>
        
        <div class="checkbox">
            <label for="subscription">
                <input type="checkbox" name="is_subscribed" id="subscription" value="1" title="<?php /* @escapeNotVerified */ echo __('General Subscription') ?>"<?php if ($block->getIsSubscribed()): ?> checked="checked"<?php endif; ?>> <?php /* @escapeNotVerified */ echo __('General Subscription') ?>
            </label>
        </div>
        
        <?php /* Extensions placeholder */ ?>
        <?php echo $block->getChildHtml('customer.form.newsletter.extra')?>
    </fieldset>

    <button type="submit" title="<?php /* @escapeNotVerified */ echo __('Save') ?>" class="btn btn-primary"><span>
        <?php /* @escapeNotVerified */ echo __('Save') ?></span>
    </button>

    <a class="btn btn-danger" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>">
        <?php /* @escapeNotVerified */ echo __('Back') ?>
    </a>
</form>
<?php /* Extensions placeholder */ ?>
<?php echo $block->getChildHtml('customer.form.newsletter.extra2')?>
