<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * New Customer block template
 *
 * @var $block \Magento\Customer\Block\Form\Login\Info
 */
?>
<?php if ($block->getRegistration()->isAllowed()): ?>
<div class="col-md-6">
    <strong role="heading" aria-level="2">
        <?php /* @escapeNotVerified */ echo __('New Customers') ?>
    </strong>

    <p><?php /* @escapeNotVerified */ echo __('Creating an account has many benefits: check out faster, keep more than one address, track orders and more.') ?></p>

    <a href="<?php /* @escapeNotVerified */ echo $block->getCreateAccountUrl() ?>" class="btn btn-primary"><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></a>
</div>
<?php endif; ?>